version: '3.9'
services:
  order-db:
    image: "postgis/postgis:14-3.3-alpine"
    environment:
      POSTGRES_DB: ordenes_service
      POSTGRES_USER: ordenes_user
      POSTGRES_PASSWORD: 123
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
  order:
    build:
      context: .
      target: service1
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      POSTGRES_URL: postgresql://ordenes_user:123@order-db:5432/ordenes_service
    volumes:
      - .:/app
    deploy:
      replicas: 2
      mode: replicated
      resources:
        limits:
          cpus: '0.2'
          memory: '50M'
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 2
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - pulsar-broker
      - order-db
  client:
    build:
      context: .
      target: service2
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker
  reporting:
    build:
      context: .
      target: reporting
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker
  service4:
    build:
      context: .
      target: service4
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker

  pulsar-broker:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m"
      PULSAR_CONF: "/pulsar/conf"
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf

volumes:
  pulsar_conf:
  pulsar_data:
  orders_data:
  esdata01:
    driver: local
