version: '3.9'
services:
  service1:
    build:
      context: .
      target: service1
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      PULSAR_TOPIC: my-topic
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker
  service2:
    build:
      context: .
      target: service2
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      PULSAR_TOPIC: my-topic
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker
  service3:
    build:
      context: .
      target: service3
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      PULSAR_TOPIC: my-topic
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker
  service4:
    build:
      context: .
      target: service4
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      PULSAR_TOPIC: my-topic
    volumes:
      - .:/app
    depends_on:
      - pulsar-broker

  pulsar-broker:
    image: apachepulsar/pulsar:2.9.1
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
