version: '3'
services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PULSAR_BROKER_URL: pulsar://pulsar-broker:6650
      PULSAR_TOPIC: my-topic
    depends_on:
      - pulsar-broker

  pulsar-broker:
    image: apachepulsar/pulsar:2.9.1
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
